### ISSUE TITLE
Add @netlify/bots as owner on crates.io

### ISSUE THREAD

**Issue by NeoLegends** [netlify/netlify-toml-rs#16]
So we can publish to crates.io from a machine account (e. g. netlify-jenkins user).

I cannot do this on my own because I'm not an owner of the library on crates.io.

Instructions here: https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

**Comment by mraerino** [comment]
```
% cargo owner --add github:netlify:bots :(
    Updating crates.io index
error: failed to invite owners to crate netlify_toml: api errors (status 200 OK): could not find the github team netlify/bots
```

**Comment by NeoLegends** [comment]
Ugh, is it perhaps because it's private somehow?

**Comment by NeoLegends** [comment]
Alternatively can you add `netlify-jenkins` as owner? That is probably already enough.

**Comment by mraerino** [comment]
i think it needs a crates account?

```
error: failed to invite owners to crate netlify_toml: api errors (status 200 OK): could not find user with login `netlify-jenkins`
```

**Comment by NeoLegends** [comment]
Going to cr(e)ate that really quick for netlify-jenkins.

**Comment by NeoLegends** [comment]
✅ let's try again!

**Comment by mraerino** [comment]
```
Owner user netlify-jenkins has been invited to be an owner of crate netlify_toml
```
